[package]
name = "add"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
doc = false
name = "cf"
path = "src/main.rs"

[dependencies]
wasm-bindgen = "0.2"